// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqlubhabeobqihxkkheo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxbHViaGFiZW9icWloeGtraGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjE1MTQsImV4cCI6MjA2NDc5NzUxNH0.pNsFy_REjDaIwR6NiAZ0Oc2DvnEktvrO7VbCi3YrOZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);